#!/bin/bash

# project 2
# machine translation

frenchtrain=$1
englishtrain=$2
frenchtest=$3

# 
# Make TWO copies of this script, one to test your very dumb translator and
# one for the noisy-channel translator your bigram model. Save them under
# the filenames 'verydumb' and 'noisychannel'.
# 
# Fill in the empty space below with whatever sequence of commands will run
# your EM training code and your decoder and print the translation to
# standard output, in the same format as the original (one sentence per 
# line, all tokens separated by single spaces). Pass your program(s) the
# arguments '$frenchtrain' and '$englishtrain' for the French and English
# training data respectively, and '$frenchtest' for whatever you want to
# translate.
#
##############################################################################
java DumbDecoder $frenchtrain $englishtrain $frenchtest -Xms4g
##############################################################################
# Run this script with the command (all on one line)
# 
#       ./langmod french-senate-0.txt english-senate-0.txt
#               french-senate-2.txt
